adding a check for required variables

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -40,14 +40,21 @@ jobs:
       - name: Get version from GitVersion
         id: gitversion
         run: |
+          set -e
           dotnet tool install --global GitVersion.Tool
-          dotnet gitversion /output json > gitversion.json
+          export PATH="$PATH:$HOME/.dotnet/tools"
+          dotnet-gitversion /output json > gitversion.json || (echo "GitVersion failed:"; cat gitversion.json || true; exit 1)
+          cat gitversion.json
           echo "version=$(jq -r .SemVer gitversion.json)" >> $GITHUB_OUTPUT
+      - name: Check required environment variables
+        run: |
+          if [ -z "${{ secrets.PACKAGES_API_KEY }}" ]; then echo "PACKAGES_API_KEY is missing!"; exit 1; fi
+          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then echo "GITHUB_TOKEN is missing!"; exit 1; fi
+          if [ -z "${{ steps.gitversion.outputs.version }}" ]; then echo "GITVERSION_NUGET_VERSION is missing!"; exit 1; fi
       - name: 'Run: Publish'
         run: ./build.cmd Publish --host GitHubActions
         env:
           PACKAGES_API_KEY: ${{ secrets.PACKAGES_API_KEY }}
-          ReadPackagesToken: ${{ secrets.READ_PACKAGES_TOKEN }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GITVERSION_NUGET_VERSION: ${{ steps.gitversion.outputs.version }}
       - name: 'Publish: output'
